receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  loki:
    endpoint: http://aaron-loki:3100/loki/api/v1/push
    default_labels_enabled:
      exporter: false
      job: true

processors:

service:
  
  pipelines:
    # traces:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [debug, zipkin, otlp]
    # metrics:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [debug, prometheus]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [loki]



      