version: "3"

networks:
  Tunnel:
    driver: bridge

services:

  carlosdb:
    image: postgres
    container_name: postgresql
    restart: always
    environment:
      - POSTGRES_USER: ticketuser
      - POSTGRES_DB: postgres
      - POSTGRES_PASSWORD: P@ssword1
    ports:
      - "5432:5432"
    networks:
      - Tunnel
    volumes:
      - ../TestTicket/20240215.01.21.01.sql:/docker-entrypoint-initdb.d/init.sql

  blazor:
   container_name: blazor
   depends_on:
     - carlosdb
   build: ..
   environment:
     - ASPNETCORE_ENVIRONMENT=Production
     - Postgres=Server=carlosdb;Database=postgres;Port=5432;User ID=ticketuser;Password=P@ssword1
   ports:
     - "5454:8080" 
   networks:
     - Tunnel

