version: "3"

services:

  carlosdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ticketuser
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: P@ssword1
    volumes:
      - ../TestTicket/20240215.01.21.01.sql:/docker-entrypoint-initdb.d/init.sql

  blazor:
   container_name: blazor
   depends_on:
     - carlosdb
   build: ..
   environment:
     - ASPNETCORE_ENVIRONMENT=Production
     - Postgres=Server=carlosdb;Database=postgres;Port=5432;User ID=ticketuser;Password=P@ssword1
   ports:
     - "4765:8080" 

  blackbox:
    # https://github.com/prometheus/blackbox_exporter/releases
   image: prom/blackbox-exporter:v0.23.0
   container_name: blackbox
   depends-on:
    - blazor
   restart: unless-stopped
   ports:
      - "4766:9115"
   volumes:
      #- /etc/localtime:/etc/localtime:ro I'm not sure I need this
      - ./blackbox/blackbox.yml:/etc/blackbox/blackbox.yml
   command: --config.file=/etc/blackbox/blackbox.yml
     
  prometheus:
    # https://github.com/prometheus/prometheus/releases
   image: prom/prometheus:v2.43.0
   container_name: prometheus
   hostname: prometheus
   restart: unless-stopped
   ports:
      - "4767:9090"
   volumes:
      #- /etc/localtime:/etc/localtime:ro Not sure I need this
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      #- prometheus:/prometheus Not sure I need this
   depends_on:
      - blackbox

  grafana:
    # https://github.com/grafana/grafana/releases
    image: grafana/grafana:9.4.7
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      #- /etc/localtime:/etc/localtime:ro Not Sure I need this
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped
    user: root
    ports:
      - "4768:3000"
    depends_on:
      - prometheus     

volumes:
  prometheus:
  grafana-data:
     

